QBShared = QBShared or {}
QBShared.VehicleHashes = {}

QBShared.Vehicles = {
	---------- Dono Wheel ----------
	["07wrx"] = {
		["name"] = "WRX Impreza STI",
		["brand"] = "Subaru",
		["model"] = "07wrx",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("07wrx"),
		["image"] = "https://cdn.discordapp.com/attachments/520646015062376459/1103140478888710175/image.png",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["18performante"] = {
		["name"] = "Hurracan Performante",
		["brand"] = "Lamborghini",
		["model"] = "18performante",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("18performante"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["22m5"] = {
		["name"] = "M5 CS",
		["brand"] = "BMW",
		["model"] = "22m5",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("22m5"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["300ZW"] = {
		["name"] = "300ZW",
		["brand"] = "Nissan",
		["model"] = "300ZW",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("300ZW"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["420X"] = {
		["name"] = "420X Drift",
		["brand"] = "Nissan",
		["model"] = "420X",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("420X"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["amgone"] = {
		["name"] = "AMG One",
		["brand"] = "Mercedes",
		["model"] = "amgone",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("amgone"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["beetleRWB"] = {
		["name"] = "Beetle RWB",
		["brand"] = "Volkswagen",
		["model"] = "beetleRWB",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("beetleRWB"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["bt62r"] = {
		["name"] = "GT 62R",
		["brand"] = "Brabham",
		["model"] = "bt62r",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("bt62r"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["durango18"] = {
		["name"] = "Durango SRT",
		["brand"] = "Dodge",
		["model"] = "durango18",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("durango18"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["ESDUCATI2K22"] = {
		["name"] = "Superleggera Modded",
		["brand"] = "Ducati",
		["model"] = "ESDUCATI2K22",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("ESDUCATI2K22"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["evo9"] = {
	    ["name"] = "Lancer Evo 9 Voltex",
		["brand"] = "Mitsubishi",
		["model"] = "evo9",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("evo9"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["GODzHCPACIFICA"] = {
		["name"] = "Pacifica Demon",
		["brand"] = "Chrysler",
		["model"] = "GODzHCPACIFICA",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("GODzHCPACIFICA"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["hycader34"] = {
		["name"] = "GT R34 Hycade",
		["brand"] = "Nissan",
		["model"] = "hycader34",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("hycader34"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["mansc8"] = {
		["name"] = "Corvette C8 Mansaug",
		["brand"] = "Chevrolet",
		["model"] = "mansc8",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("mansc8"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["p1lm"] = {
		["name"] = "p1",
		["brand"] = "McLaren",
		["model"] = "p1lm",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("p1lm"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["pruf"] = {
		["name"] = "GT3 RS",
		["brand"] = "Porsche",
		["model"] = "pruf",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("pruf"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["pursport"] = {
		["name"] = "Chiron Pur Sport",
		["brand"] = "Bugatti",
		["model"] = "pursport",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("pursport"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["r8hycade"] = {
		["name"] = "R8 Hycade",
		["brand"] = "Audi",
		["model"] = "r8hycade",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("r8hycade"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	["ramlow"] = {
		["name"] = "Ram Low Rider",
		["brand"] = "Dodge",
		["model"] = "ramlow",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("ramlow"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
["rmodg65"] = {
		["name"] = "G65",
		["brand"] = "Mercedes Benz",
		["model"] = "rmodg65",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("rmodg65"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
["rmodjeep"] = {
		["name"] = "Cherokee TrackHawk",
		["brand"] = "Jeep",
		["model"] = "rmodjeep",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("rmodjeep"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
["rmodlfa"] = {
		["name"] = "LFA",
		["brand"] = "Lexus",
		["model"] = "rmodlfa",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("rmodlfa"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
["rs7wide"] = {
		["name"] = "RS7 Wide Body",
		["brand"] = "Audi",
		["model"] = "rs7wide",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("rs7wide"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
["teslapd"] = {
		["name"] = "Model S Prior",
		["brand"] = "Tesla",
		["model"] = "teslapd",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("teslapd"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
["zlay_asap"] = {
		["name"] = "190E A$AP Rocky",
		["brand"] = "Mercedes Benz",
		["model"] = "zlay_asap",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("zlay_asap"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
["zlay_e36"] = {
		["name"] = "E36 Drift",
		["brand"] = "BMW",
		["model"] = "zlay_e36",
		---["price"] = 0,
		["category"] = "Dono",
		["hash"] = GetHashKey("zlay_e36"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Dono",
	},
	---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
	---------- Police Department ----------
	
	--- High Command ---
	
---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
	

	--- Command ---
	
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},

	--- Patrol ---

		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
	--- Cadet ---
	
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
	--- Unmarked ---
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},

	---------- EMS ----------
	
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
	---------- LUX ----------
	
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
	---------- PDM ----------
	
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},

	---------- Gangs ----------
	
		["1016urus"] = {
		["name"] = "Urus",
		["brand"] = "Lamborghini",
		["model"] = "1016urus",
		---["price"] = 0,
		["category"] = "Gangs",
		["hash"] = GetHashKey("1016urus"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Gangs",
	},
	["benze55"] = {
		["name"] = "E55",
		["brand"] = "Mercedes Benz",
		["model"] = "benze55",
		---["price"] = 0,
		["category"] = "Gangs",
		["hash"] = GetHashKey("benze55"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "Gangs",
	},
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},

	---------- One of One's (Private) ----------
	
	["488lbspider"] = {
		["name"] = "488 Spider Liberty Walk",
		["brand"] = "Ferrari",
		["model"] = "488lbspider",
		---["price"] = 0,
		["category"] = "Staff Freshie",
		["hash"] = GetHashKey("488lbspider"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		["shop"] = "1 of 1",
	},
		---["FileName"] = {
		---["name"] = "ModelName",
		---["brand"] = "MakeName",
		---["model"] = "FileName",
		---["price"] = 0,
		---["category"] = "XXX",
		---["hash"] = GetHashKey("FileName"),
		---["image"] = "LINK",
		---["trunkspace"] = 0,
		---["trunkslots"] = 0,
		---["shop"] = "Dealership",
	},
}

for _, v in pairs(QBSared.Vehicles) do
	QBshared.VehicleHashes[v.hash] = v
end