Citizen.CreateThread(function()
     AddTextEntry('07wrx', 'Subaru WRX Impreza STI')
     AddTextEntry('18performante', 'Lamborghini Hurracan Performante')
     AddTextEntry('22m5', 'BMW M5 CS')
     AddTextEntry('300ZW', 'Nissan 300ZW')
     AddTextEntry('420X', 'Nissan 420X Drift')
	 AddTextEntry('488lbspider', 'Ferraro 488 Spider Liberty Walk')
	 AddTextEntry('1016urus', 'Lamborghini Urus')
	 AddTextEntry('beetleRWB', 'Volkswagen Beetle RWB')
	 AddTextEntry('amgone', 'Mercedes AMG One')
	 AddTextEntry('bmw07', 'BMW X7')
     AddTextEntry('benze55', 'Mercedes Benz E55')
	 AddTextEntry('bt62r', 'Brabham GT62R')
	 AddTextEntry('durango18', 'Dodge Durango SRT')
	 AddTextEntry('ESDUCATI2K22', 'Ducati Superleggera Modded')
	 AddTextEntry('evo9', 'Mitsubishi Lancer Evo 9 Voltex')
	 AddTextEntry('GODzHCPACIFICA', 'Chrysler Pacifica Demon')
	 AddTextEntry('gt17', 'Ford GT')
	 AddTextEntry('hycader34', 'Nissan GT R34 Hycade')
	 AddTextEntry('mansc8', 'Chevrolet Corvette C8 Mansaug')
	 AddTextEntry('p1lm', 'McLaren P1')
	 AddTextEntry('pruf', 'Porsche GT3 RS')
	 AddTextEntry('pursport', 'Bugatti Chiron Pur Sport')
	 AddTextEntry('r8hycade', 'Audi R8 Hycade')
	 AddTextEntry('ramlow', 'Dodge Ram Low Rider')
	 AddTextEntry('rmodg65', 'Mercedes Benz G65')
	 AddTextEntry('rmodjeep', 'Jeep Cherokee TrackHawk')
	 AddTextEntry('rmodlfa', 'Lexus LFA')
	 AddTextEntry('rs7wide', 'Audi RS7 Wide Body')
	 AddTextEntry('teslapd', 'Tesla Model S Prior')
	 AddTextEntry('zlay_asap', 'Mercedes Benz 190E A$AP Rocky')
	 AddTextEntry('zlay_e36', 'BMW E36 Drift')
	 ---AddTextEntry('FileName', 'VehicleName')
	 ---AddTextEntry('FileName', 'VehicleName')

end